#!/bin/bash -x
set -e
for i in hw3 hw3a ; do ../../816-tcc -I. -Wl,--oformat,binary -o $i.asm -c $i.c ; done
for i in hw3 hw3a ; do ../../../wla_dx/wla-65816 -io $i.asm $i.obj ; done
../../../wla_dx/wlalink/wlalink -vS test.lnk test.smc
gcc -m32 hw3.c hw3a.c
./a.out >output.gcc || true
../../../snes9x/snes9x test.smc >output.snes
xset r on
diff -u output.gcc output.snes
rm -f hw3.asm hw3a.asm test.sym test.smc hw3.obj hw3a.obj output.gcc a.out output.snes
